/**
 * CMS Router — Super Admin Panel
 * Only accessible by the platform owner (verified via OWNER_OPEN_ID).
 * Provides: user management, role assignment, activity logs, platform settings, traffic stats,
 * admin secret key management (with expiry), and pending registration approval queue.
 */
import { z } from "zod";
import { router, publicProcedure } from "../_core/trpc";
import { TRPCError } from "@trpc/server";
import { getDb } from "../db";
import { users, activityLog, platformSettings, adminRegistrationRequests, llmQuotas, superAdminCredentials, keyHistory, userSessions, siteContent } from "../../drizzle/schema";
import { eq, desc, sql, like, and, gte, lte, count } from "drizzle-orm";
import { notifyOwner } from "../_core/notification";
import * as db from "../db";
import crypto from "crypto";
import bcrypt from "bcryptjs";

// Owner-only middleware: validates the super admin token from the x-sa-token header.
// The token is generated by superAdminLogin after successful username+password authentication.
const ownerOnly = publicProcedure.use(async ({ ctx, next }) => {
  const token = ctx.req.headers["x-sa-token"] as string | undefined;
  if (!token) {
    throw new TRPCError({ code: "NOT_FOUND", message: "Not found" });
  }
  try {
    const payload = JSON.parse(Buffer.from(token, "base64").toString());
    if (!payload.superAdmin || payload.exp < Date.now()) {
      throw new TRPCError({ code: "NOT_FOUND", message: "Not found" });
    }
    // Inject a synthetic user so ctx.user references work throughout CMS procedures
    const syntheticUser = {
      id: payload.credId || 0,
      openId: process.env.OWNER_OPEN_ID || "super_admin",
      email: payload.username || "super_admin",
      name: payload.username || "Super Admin",
      role: "admin" as const,
      avatarUrl: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      usedKey: null,
    };
    return next({ ctx: { ...ctx, user: syntheticUser as any } });
  } catch {
    throw new TRPCError({ code: "NOT_FOUND", message: "Not found" });
  }
});

export const cmsRouter = router({
  // ─── Verify CMS Access ───────────────────────────────────────────────────────
  verifyAccess: ownerOnly.query(async ({ ctx }) => {
    return { authorized: true, user: { id: ctx.user.id, email: ctx.user.email, role: ctx.user.role } };
  }),

  // ─── User Management ─────────────────────────────────────────────────────────
  listUsers: ownerOnly
    .input(z.object({
      page: z.number().min(1).default(1),
      limit: z.number().min(1).max(100).default(50),
      search: z.string().optional(),
      role: z.enum(["admin", "user"]).optional(),
    }).optional())
    .query(async ({ input }) => {
      const drizzleDb = await getDb();
      if (!drizzleDb) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      const { page = 1, limit = 50, search, role } = input || {};
      const offset = (page - 1) * limit;

      const conditions = [];
      if (search) {
        conditions.push(
          sql`(${users.email} LIKE ${`%${search}%`} OR ${users.name} LIKE ${`%${search}%`})`
        );
      }
      if (role) {
        conditions.push(eq(users.role, role));
      }

      const whereClause = conditions.length > 0 ? and(...conditions) : undefined;

      const [userList, totalResult] = await Promise.all([
        drizzleDb.select().from(users).where(whereClause).orderBy(desc(users.createdAt)).limit(limit).offset(offset),
        drizzleDb.select({ count: count() }).from(users).where(whereClause),
      ]);

      return {
        users: userList.map((u: typeof users.$inferSelect) => ({
          id: u.id,
          openId: u.openId,
          name: u.name,
          email: u.email,
          role: u.role,
          loginMethod: u.loginMethod,
          createdAt: u.createdAt,
          lastSignedIn: u.lastSignedIn,
        })),
        total: totalResult[0]?.count || 0,
        page,
        limit,
      };
    }),

  // Promote/demote user role
  updateUserRole: ownerOnly
    .input(z.object({
      userId: z.number(),
      role: z.enum(["admin", "user"]),
    }))
    .mutation(async ({ input, ctx }) => {
      const drizzleDb = await getDb();
      if (!drizzleDb) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      const [target] = await drizzleDb.select().from(users).where(eq(users.id, input.userId)).limit(1);
      if (!target) throw new TRPCError({ code: "NOT_FOUND", message: "User not found" });

      // Prevent self-demotion
      if (target.id === ctx.user.id && input.role !== "admin") {
        throw new TRPCError({ code: "BAD_REQUEST", message: "Cannot demote yourself" });
      }

      await drizzleDb.update(users).set({ role: input.role }).where(eq(users.id, input.userId));

      // Log the action
      await drizzleDb.insert(activityLog).values({
        userId: ctx.user.id,
        userEmail: ctx.user.email || undefined,
        userRole: ctx.user.role,
        action: "cms.updateRole",
        target: `user:${input.userId}`,
        details: JSON.stringify({ oldRole: target.role, newRole: input.role, targetEmail: target.email }),
      });

      return { success: true };
    }),

  // Delete user
  deleteUser: ownerOnly
    .input(z.object({ userId: z.number() }))
    .mutation(async ({ input, ctx }) => {
      const drizzleDb = await getDb();
      if (!drizzleDb) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      if (input.userId === ctx.user.id) {
        throw new TRPCError({ code: "BAD_REQUEST", message: "Cannot delete yourself" });
      }
      const [target] = await drizzleDb.select().from(users).where(eq(users.id, input.userId)).limit(1);
      if (!target) throw new TRPCError({ code: "NOT_FOUND", message: "User not found" });

      await drizzleDb.delete(users).where(eq(users.id, input.userId));

      await drizzleDb.insert(activityLog).values({
        userId: ctx.user.id,
        userEmail: ctx.user.email || undefined,
        userRole: ctx.user.role,
        action: "cms.deleteUser",
        target: `user:${input.userId}`,
        details: JSON.stringify({ deletedEmail: target.email, deletedRole: target.role }),
      });

      return { success: true };
    }),

  // ─── Activity Logs ────────────────────────────────────────────────────────────
  getActivityLogs: ownerOnly
    .input(z.object({
      page: z.number().min(1).default(1),
      limit: z.number().min(1).max(200).default(50),
      action: z.string().optional(),
      userId: z.number().optional(),
    }).optional())
    .query(async ({ input }) => {
      const drizzleDb = await getDb();
      if (!drizzleDb) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      const { page = 1, limit = 50, action, userId } = input || {};
      const offset = (page - 1) * limit;

      const conditions = [];
      if (action) conditions.push(like(activityLog.action, `%${action}%`));
      if (userId) conditions.push(eq(activityLog.userId, userId));

      const whereClause = conditions.length > 0 ? and(...conditions) : undefined;

      const [logs, totalResult] = await Promise.all([
        drizzleDb.select().from(activityLog).where(whereClause).orderBy(desc(activityLog.createdAt)).limit(limit).offset(offset),
        drizzleDb.select({ count: count() }).from(activityLog).where(whereClause),
      ]);

      return { logs, total: totalResult[0]?.count || 0, page, limit };
    }),

  // ─── Platform Settings ────────────────────────────────────────────────────────
  getSettings: ownerOnly.query(async () => {
    const drizzleDb = await getDb();
    if (!drizzleDb) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });
    const settings = await drizzleDb.select().from(platformSettings);
    return settings;
  }),

  updateSetting: ownerOnly
    .input(z.object({
      key: z.string(),
      value: z.string(),
    }))
    .mutation(async ({ input, ctx }) => {
      const drizzleDb = await getDb();
      if (!drizzleDb) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      const existing = await drizzleDb.select().from(platformSettings).where(eq(platformSettings.key, input.key)).limit(1);
      if (existing.length === 0) {
        await drizzleDb.insert(platformSettings).values({ key: input.key, value: input.value, updatedBy: ctx.user.id });
      } else {
        await drizzleDb.update(platformSettings).set({ value: input.value, updatedBy: ctx.user.id }).where(eq(platformSettings.key, input.key));
      }

      await drizzleDb.insert(activityLog).values({
        userId: ctx.user.id,
        userEmail: ctx.user.email || undefined,
        userRole: ctx.user.role,
        action: "cms.updateSetting",
        target: `setting:${input.key}`,
        details: JSON.stringify({ newValue: input.key === "admin_secret_key" ? "***" : input.value }),
      });

      return { success: true };
    }),

  // ─── Traffic Stats ────────────────────────────────────────────────────────────
  getTrafficStats: ownerOnly.query(async () => {
    const drizzleDb = await getDb();
    if (!drizzleDb) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

    // User counts by role
    const roleCounts = await drizzleDb
      .select({ role: users.role, count: count() })
      .from(users)
      .groupBy(users.role);

    // Recent registrations (last 7 days)
    const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
    const recentRegistrations = await drizzleDb
      .select({ count: count() })
      .from(users)
      .where(gte(users.createdAt, sevenDaysAgo));

    // Activity in last 24h
    const oneDayAgo = new Date(Date.now() - 24 * 60 * 60 * 1000);
    const recentActivity = await drizzleDb
      .select({ action: activityLog.action, count: count() })
      .from(activityLog)
      .where(gte(activityLog.createdAt, oneDayAgo))
      .groupBy(activityLog.action)
      .orderBy(desc(count()))
      .limit(20);

    // Active users (logged in last 7 days)
    const activeUsers = await drizzleDb
      .select({ count: count() })
      .from(users)
      .where(gte(users.lastSignedIn, sevenDaysAgo));

    // Total activity count
    const totalActivity = await drizzleDb.select({ count: count() }).from(activityLog);

    // Pending registration requests
    const pendingCount = await drizzleDb
      .select({ count: count() })
      .from(adminRegistrationRequests)
      .where(eq(adminRegistrationRequests.status, "pending"));

    return {
      totalUsers: roleCounts.reduce((sum: number, r: { role: string; count: number }) => sum + r.count, 0),
      roleCounts: Object.fromEntries(roleCounts.map((r: { role: string; count: number }) => [r.role, r.count])),
      recentRegistrations: recentRegistrations[0]?.count || 0,
      activeUsersLast7d: activeUsers[0]?.count || 0,
      totalActivityLogs: totalActivity[0]?.count || 0,
      pendingRegistrations: pendingCount[0]?.count || 0,
      recentActivity,
    };
  }),

  // ─── Admin Secret Key Management (with Expiry) ────────────────────────────────
  getAdminSecretKey: ownerOnly.query(async () => {
    const drizzleDb = await getDb();
    if (!drizzleDb) return { key: process.env.ADMIN_SECRET_KEY || "", expiresAt: null, expiryDays: null };
    const [keySetting] = await drizzleDb.select().from(platformSettings).where(eq(platformSettings.key, "admin_secret_key")).limit(1);
    const [expirySetting] = await drizzleDb.select().from(platformSettings).where(eq(platformSettings.key, "admin_key_expires_at")).limit(1);
    const [expiryDaysSetting] = await drizzleDb.select().from(platformSettings).where(eq(platformSettings.key, "admin_key_expiry_days")).limit(1);

    return {
      key: keySetting?.value || process.env.ADMIN_SECRET_KEY || "",
      expiresAt: expirySetting?.value || null,
      expiryDays: expiryDaysSetting?.value || null,
    };
  }),

  rotateAdminSecretKey: ownerOnly
    .input(z.object({
      newKey: z.string().min(8),
      expiryDays: z.number().min(0).max(365).optional(), // 0 = never expires
      label: z.string().optional(), // optional label for the key
    }))
    .mutation(async ({ input, ctx }) => {
      const drizzleDb = await getDb();
      if (!drizzleDb) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      // Deactivate previous key in key_history
      await drizzleDb.update(keyHistory).set({ isActive: false }).where(eq(keyHistory.isActive, true));

      // Update or insert the key
      const existing = await drizzleDb.select().from(platformSettings).where(eq(platformSettings.key, "admin_secret_key")).limit(1);
      if (existing.length === 0) {
        await drizzleDb.insert(platformSettings).values({ key: "admin_secret_key", value: input.newKey, updatedBy: ctx.user.id });
      } else {
        await drizzleDb.update(platformSettings).set({ value: input.newKey, updatedBy: ctx.user.id }).where(eq(platformSettings.key, "admin_secret_key"));
      }

      // Record new key in key_history
      const expiresAtDate = input.expiryDays && input.expiryDays > 0
        ? new Date(Date.now() + input.expiryDays * 24 * 60 * 60 * 1000)
        : null;
      await drizzleDb.insert(keyHistory).values({
        keyValue: input.newKey,
        createdBy: ctx.user.email || ctx.user.name || "owner",
        isActive: true,
        expiresAt: expiresAtDate,
        registrationCount: 0,
        label: input.label || null,
      });

      // Set expiry if provided
      if (input.expiryDays !== undefined) {
        const expiresAt = input.expiryDays > 0
          ? new Date(Date.now() + input.expiryDays * 24 * 60 * 60 * 1000).toISOString()
          : "never";

        // Update expiry timestamp
        const existingExpiry = await drizzleDb.select().from(platformSettings).where(eq(platformSettings.key, "admin_key_expires_at")).limit(1);
        if (existingExpiry.length === 0) {
          await drizzleDb.insert(platformSettings).values({ key: "admin_key_expires_at", value: expiresAt, updatedBy: ctx.user.id });
        } else {
          await drizzleDb.update(platformSettings).set({ value: expiresAt, updatedBy: ctx.user.id }).where(eq(platformSettings.key, "admin_key_expires_at"));
        }

        // Store the expiry days setting
        const existingDays = await drizzleDb.select().from(platformSettings).where(eq(platformSettings.key, "admin_key_expiry_days")).limit(1);
        if (existingDays.length === 0) {
          await drizzleDb.insert(platformSettings).values({ key: "admin_key_expiry_days", value: String(input.expiryDays), updatedBy: ctx.user.id });
        } else {
          await drizzleDb.update(platformSettings).set({ value: String(input.expiryDays), updatedBy: ctx.user.id }).where(eq(platformSettings.key, "admin_key_expiry_days"));
        }
      }

      // Log the action
      await drizzleDb.insert(activityLog).values({
        userId: ctx.user.id,
        userEmail: ctx.user.email || undefined,
        userRole: ctx.user.role,
        action: "cms.rotateSecretKey",
        target: "admin_secret_key",
        details: JSON.stringify({ note: "Key rotated", expiryDays: input.expiryDays ?? "unchanged" }),
      });

      // Send notification to owner
      try {
        await notifyOwner({
          title: "🔑 Admin Secret Key Rotated",
          content: `The admin registration key was rotated by ${ctx.user.email || ctx.user.name || "unknown"} at ${new Date().toISOString()}.\n\nExpiry: ${input.expiryDays ? `${input.expiryDays} days` : "never"}\n\nOld registration links will no longer work.`,
        });
      } catch { /* non-critical */ }

      return { success: true };
    }),

  // Generate a random key
  generateRandomKey: ownerOnly.query(async () => {
    const key = crypto.randomBytes(24).toString("base64url");
    return { key };
  }),

  // ─── Pending Registration Approval Queue ──────────────────────────────────────
  listPendingRegistrations: ownerOnly
    .input(z.object({
      status: z.enum(["pending", "approved", "rejected", "all"]).default("pending"),
      page: z.number().min(1).default(1),
      limit: z.number().min(1).max(100).default(50),
    }).optional())
    .query(async ({ input }) => {
      const drizzleDb = await getDb();
      if (!drizzleDb) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      const { status = "pending", page = 1, limit = 50 } = input || {};
      const offset = (page - 1) * limit;

      const conditions = [];
      if (status !== "all") {
        conditions.push(eq(adminRegistrationRequests.status, status));
      }
      const whereClause = conditions.length > 0 ? and(...conditions) : undefined;

      const [requests, totalResult] = await Promise.all([
        drizzleDb.select().from(adminRegistrationRequests).where(whereClause).orderBy(desc(adminRegistrationRequests.requestedAt)).limit(limit).offset(offset),
        drizzleDb.select({ count: count() }).from(adminRegistrationRequests).where(whereClause),
      ]);

      return {
        requests: requests.map(r => ({
          id: r.id,
          email: r.email,
          name: r.name,
          status: r.status,
          ipAddress: r.ipAddress,
          usedKey: r.usedKey,
          requestedAt: r.requestedAt,
          reviewedAt: r.reviewedAt,
          reviewedBy: r.reviewedBy,
          notes: r.notes,
        })),
        total: totalResult[0]?.count || 0,
        page,
        limit,
      };
    }),

  // Count pending registrations (for badge)
  pendingCount: ownerOnly.query(async () => {
    const drizzleDb = await getDb();
    if (!drizzleDb) return { count: 0 };
    const [result] = await drizzleDb.select({ count: count() }).from(adminRegistrationRequests).where(eq(adminRegistrationRequests.status, "pending"));
    return { count: result?.count || 0 };
  }),

  approveRegistration: ownerOnly
    .input(z.object({ requestId: z.number() }))
    .mutation(async ({ input, ctx }) => {
      const drizzleDb = await getDb();
      if (!drizzleDb) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      const [request] = await drizzleDb.select().from(adminRegistrationRequests).where(eq(adminRegistrationRequests.id, input.requestId)).limit(1);
      if (!request) throw new TRPCError({ code: "NOT_FOUND", message: "Request not found" });
      if (request.status !== "pending") throw new TRPCError({ code: "BAD_REQUEST", message: "Request already processed" });

      // Check if email already exists as a user
      const existingUser = await db.getUserByEmail(request.email.toLowerCase().trim());
      if (existingUser) {
        // Promote existing user to admin
        await db.upsertUser({ openId: existingUser.openId, role: "admin" });
      } else {
        // Create new admin user from the request
        const openId = `local_${crypto.randomUUID()}`;
        await db.upsertUser({
          openId,
          name: request.name || request.email.split("@")[0],
          email: request.email.toLowerCase().trim(),
          passwordHash: request.passwordHash,
          role: "admin",
          loginMethod: "email",
          lastSignedIn: new Date(),
        });
      }

      // Mark request as approved
      await drizzleDb.update(adminRegistrationRequests).set({
        status: "approved",
        reviewedAt: new Date(),
        reviewedBy: ctx.user.id,
      }).where(eq(adminRegistrationRequests.id, input.requestId));

      // Log
      await drizzleDb.insert(activityLog).values({
        userId: ctx.user.id,
        userEmail: ctx.user.email || undefined,
        userRole: ctx.user.role,
        action: "cms.approveRegistration",
        target: `request:${input.requestId}`,
        details: JSON.stringify({ approvedEmail: request.email }),
      });

      // Notify owner
      try {
        await notifyOwner({
          title: "✅ Admin Registration Approved",
          content: `Admin registration for ${request.email} was approved by ${ctx.user.email || "unknown"} at ${new Date().toISOString()}.`,
        });
      } catch { /* non-critical */ }

      return { success: true };
    }),

  rejectRegistration: ownerOnly
    .input(z.object({
      requestId: z.number(),
      notes: z.string().optional(),
    }))
    .mutation(async ({ input, ctx }) => {
      const drizzleDb = await getDb();
      if (!drizzleDb) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      const [request] = await drizzleDb.select().from(adminRegistrationRequests).where(eq(adminRegistrationRequests.id, input.requestId)).limit(1);
      if (!request) throw new TRPCError({ code: "NOT_FOUND", message: "Request not found" });
      if (request.status !== "pending") throw new TRPCError({ code: "BAD_REQUEST", message: "Request already processed" });

      await drizzleDb.update(adminRegistrationRequests).set({
        status: "rejected",
        reviewedAt: new Date(),
        reviewedBy: ctx.user.id,
        notes: input.notes || null,
      }).where(eq(adminRegistrationRequests.id, input.requestId));

      // Log
      await drizzleDb.insert(activityLog).values({
        userId: ctx.user.id,
        userEmail: ctx.user.email || undefined,
        userRole: ctx.user.role,
        action: "cms.rejectRegistration",
        target: `request:${input.requestId}`,
        details: JSON.stringify({ rejectedEmail: request.email, notes: input.notes }),
      });

      return { success: true };
    }),

  // ─── LLM Quota Management ─────────────────────────────────────────────────

  listQuotas: ownerOnly.query(async () => {
    const drizzleDb = await getDb();
    if (!drizzleDb) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });
    const quotas = await drizzleDb
      .select({
        id: llmQuotas.id,
        userId: llmQuotas.userId,
        dailyLimit: llmQuotas.dailyLimit,
        monthlyLimit: llmQuotas.monthlyLimit,
        usedToday: llmQuotas.usedToday,
        usedThisMonth: llmQuotas.usedThisMonth,
        lastDailyReset: llmQuotas.lastDailyReset,
        lastMonthlyReset: llmQuotas.lastMonthlyReset,
        userName: users.name,
        userEmail: users.email,
        userRole: users.role,
      })
      .from(llmQuotas)
      .leftJoin(users, eq(llmQuotas.userId, users.id))
      .orderBy(desc(llmQuotas.usedThisMonth));
    return quotas;
  }),

  setQuota: ownerOnly
    .input(z.object({
      userId: z.number(),
      dailyLimit: z.number().min(0).max(10000),
      monthlyLimit: z.number().min(0).max(100000),
    }))
    .mutation(async ({ input, ctx }) => {
      const drizzleDb = await getDb();
      if (!drizzleDb) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });
      // Upsert: create if not exists, update if exists
      const existing = await drizzleDb.select().from(llmQuotas).where(eq(llmQuotas.userId, input.userId)).limit(1);
      if (existing.length > 0) {
        await drizzleDb.update(llmQuotas)
          .set({ dailyLimit: input.dailyLimit, monthlyLimit: input.monthlyLimit })
          .where(eq(llmQuotas.userId, input.userId));
      } else {
        await drizzleDb.insert(llmQuotas).values({
          userId: input.userId,
          dailyLimit: input.dailyLimit,
          monthlyLimit: input.monthlyLimit,
        });
      }

      // Log
      await drizzleDb.insert(activityLog).values({
        userId: ctx.user.id,
        userEmail: ctx.user.email || undefined,
        userRole: ctx.user.role,
        action: "cms.setQuota",
        target: `user:${input.userId}`,
        details: JSON.stringify({ dailyLimit: input.dailyLimit, monthlyLimit: input.monthlyLimit }),
      });

      return { success: true };
    }),

  resetQuota: ownerOnly
    .input(z.object({
      userId: z.number(),
      resetType: z.enum(["daily", "monthly", "both"]),
    }))
    .mutation(async ({ input, ctx }) => {
      const drizzleDb = await getDb();
      if (!drizzleDb) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });
      const now = new Date();
      const updates: Record<string, unknown> = {};
      if (input.resetType === "daily" || input.resetType === "both") {
        updates.usedToday = 0;
        updates.lastDailyReset = now;
      }
      if (input.resetType === "monthly" || input.resetType === "both") {
        updates.usedThisMonth = 0;
        updates.lastMonthlyReset = now;
      }
      await drizzleDb.update(llmQuotas).set(updates).where(eq(llmQuotas.userId, input.userId));

      // Log
      await drizzleDb.insert(activityLog).values({
        userId: ctx.user.id,
        userEmail: ctx.user.email || undefined,
        userRole: ctx.user.role,
        action: "cms.resetQuota",
        target: `user:${input.userId}`,
        details: JSON.stringify({ resetType: input.resetType }),
      });

      return { success: true };
    }),

  bulkSetQuota: ownerOnly
    .input(z.object({
      dailyLimit: z.number().min(0).max(10000),
      monthlyLimit: z.number().min(0).max(100000),
    }))
    .mutation(async ({ input, ctx }) => {
      const drizzleDb = await getDb();
      if (!drizzleDb) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });
      // Update all existing quotas
      await drizzleDb.update(llmQuotas)
        .set({ dailyLimit: input.dailyLimit, monthlyLimit: input.monthlyLimit });

      // Log
      await drizzleDb.insert(activityLog).values({
        userId: ctx.user.id,
        userEmail: ctx.user.email || undefined,
        userRole: ctx.user.role,
        action: "cms.bulkSetQuota",
        details: JSON.stringify({ dailyLimit: input.dailyLimit, monthlyLimit: input.monthlyLimit }),
      });

      return { success: true };
    }),

  // ─── Dual-Layer Auth: Super Admin Login ────────────────────────────────────
  // Layer 1: OAuth session must exist (ctx.user from cookie)
  // Layer 2: Validate super-admin username + password from DB
  superAdminLogin: publicProcedure
    .input(z.object({
      username: z.string().min(1),
      password: z.string().min(1),
    }))
    .mutation(async ({ ctx, input }) => {
      const drizzleDb = await getDb();
      if (!drizzleDb) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      // Find the super admin credentials
      const [cred] = await drizzleDb.select().from(superAdminCredentials)
        .where(eq(superAdminCredentials.username, input.username))
        .limit(1);

      if (!cred) {
        throw new TRPCError({ code: "UNAUTHORIZED", message: "Invalid credentials" });
      }

      // Check if account is locked
      if (cred.lockedUntil && new Date(cred.lockedUntil) > new Date()) {
        const remainingMs = new Date(cred.lockedUntil).getTime() - Date.now();
        const remainingMin = Math.ceil(remainingMs / 60000);
        throw new TRPCError({ code: "TOO_MANY_REQUESTS", message: `Account locked. Try again in ${remainingMin} minutes.` });
      }

      // Validate password
      const valid = await bcrypt.compare(input.password, cred.passwordHash);
      if (!valid) {
        // Increment failed attempts
        const newAttempts = cred.failedAttempts + 1;
        const updates: any = { failedAttempts: newAttempts };
        if (newAttempts >= 3) {
          // Lock for 15 minutes after 3 failed attempts
          updates.lockedUntil = new Date(Date.now() + 15 * 60 * 1000);
        }
        await drizzleDb.update(superAdminCredentials)
          .set(updates)
          .where(eq(superAdminCredentials.id, cred.id));
        throw new TRPCError({ code: "UNAUTHORIZED", message: "Invalid credentials" });
      }

      // Success — reset failed attempts and update lastLoginAt
      await drizzleDb.update(superAdminCredentials)
        .set({ failedAttempts: 0, lockedUntil: null, lastLoginAt: new Date() })
        .where(eq(superAdminCredentials.id, cred.id));

            // Generate a super-admin session token (stored in sessionStorage)
      const sessionPayload = {
        credId: cred.id,
        username: cred.username,
        superAdmin: true,
        iat: Date.now(),
        exp: Date.now() + 4 * 60 * 60 * 1000, // 4 hours
      };
      const token = Buffer.from(JSON.stringify(sessionPayload)).toString("base64");
      // Log the login
      await drizzleDb.insert(activityLog).values({
        userId: cred.id,
        userEmail: cred.username,
        userRole: "super_admin",
        action: "cms.superAdminLogin",
        details: JSON.stringify({ username: input.username }),
      });

      return { success: true, token };
    }),

  // ─── Check Super Admin Session ─────────────────────────────────────────────
  // Validates that both layers are active
  checkSuperAdminSession: publicProcedure
    .input(z.object({ token: z.string() }))
    .query(async ({ ctx, input }) => {
      // Validate the super-admin token
      try {
        const payload = JSON.parse(Buffer.from(input.token, "base64").toString());
        if (!payload.superAdmin) {
          return { valid: false, reason: "invalid_token" };
        }
        if (payload.exp < Date.now()) {
          return { valid: false, reason: "token_expired" };
        }
        return { valid: true };
      } catch {
        return { valid: false, reason: "invalid_token" };
      }
    }),

  // ─── Change Super Admin Password ───────────────────────────────────────────
  changeSuperAdminPassword: ownerOnly
    .input(z.object({
      currentPassword: z.string().min(1),
      newPassword: z.string().min(8),
    }))
    .mutation(async ({ ctx, input }) => {
      const drizzleDb = await getDb();
      if (!drizzleDb) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      // Get the first (and only) super admin credential
      const [cred] = await drizzleDb.select().from(superAdminCredentials).limit(1);
      if (!cred) {
        throw new TRPCError({ code: "NOT_FOUND", message: "No super admin credentials found" });
      }

      // Validate current password
      const valid = await bcrypt.compare(input.currentPassword, cred.passwordHash);
      if (!valid) {
        throw new TRPCError({ code: "UNAUTHORIZED", message: "Current password is incorrect" });
      }

      // Hash and update new password
      const newHash = await bcrypt.hash(input.newPassword, 12);
      await drizzleDb.update(superAdminCredentials)
        .set({ passwordHash: newHash })
        .where(eq(superAdminCredentials.id, cred.id));

      // Log
      await drizzleDb.insert(activityLog).values({
        userId: ctx.user.id,
        userEmail: ctx.user.email || undefined,
        userRole: ctx.user.role,
        action: "cms.changeSuperAdminPassword",
        details: JSON.stringify({ timestamp: new Date().toISOString() }),
      });

      // Notify owner
      await notifyOwner({
        title: "Super Admin Password Changed",
        content: `Super admin password was changed at ${new Date().toISOString()}.`,
      });

      return { success: true };
    }),

  // ─── Key History Tracking ─────────────────────────────────────────────────
  getKeyHistory: ownerOnly.query(async () => {
    const drizzleDb = await getDb();
    if (!drizzleDb) return [];
    const history = await drizzleDb.select().from(keyHistory).orderBy(desc(keyHistory.createdAt));
    return history;
  }),

  // Get users who registered with a specific key
  getKeyAffectedUsers: ownerOnly
    .input(z.object({ keyValue: z.string() }))
    .query(async ({ input }) => {
      const drizzleDb = await getDb();
      if (!drizzleDb) return [];

      // Find registration requests that used this key
      const requests = await drizzleDb.select({
        id: adminRegistrationRequests.id,
        email: adminRegistrationRequests.email,
        name: adminRegistrationRequests.name,
        status: adminRegistrationRequests.status,
        requestedAt: adminRegistrationRequests.requestedAt,
      }).from(adminRegistrationRequests)
        .where(eq(adminRegistrationRequests.usedKey, input.keyValue))
        .orderBy(desc(adminRegistrationRequests.requestedAt));

      return requests;
    }),

  // Get registration key used by a specific user (by email)
  getUserRegistrationKey: ownerOnly
    .input(z.object({ email: z.string() }))
    .query(async ({ input }) => {
      const drizzleDb = await getDb();
      if (!drizzleDb) return null;

      const [request] = await drizzleDb.select({
        usedKey: adminRegistrationRequests.usedKey,
        requestedAt: adminRegistrationRequests.requestedAt,
      }).from(adminRegistrationRequests)
        .where(eq(adminRegistrationRequests.email, input.email.toLowerCase().trim()))
        .limit(1);

      return request || null;
    }),

  // ─── User Session Management ──────────────────────────────────────────────
  getActiveSessions: ownerOnly.query(async () => {
    const drizzleDb = await getDb();
    if (!drizzleDb) return [];

    const now = new Date();
    const sessions = await drizzleDb.select({
      id: userSessions.id,
      userId: userSessions.userId,
      sessionDurationMinutes: userSessions.sessionDurationMinutes,
      lastActivity: userSessions.lastActivity,
      expiresAt: userSessions.expiresAt,
      isActive: userSessions.isActive,
      ipAddress: userSessions.ipAddress,
      createdAt: userSessions.createdAt,
      userName: users.name,
      userEmail: users.email,
      userRole: users.role,
    }).from(userSessions)
      .leftJoin(users, eq(userSessions.userId, users.id))
      .where(and(eq(userSessions.isActive, true), gte(userSessions.expiresAt, now)))
      .orderBy(desc(userSessions.createdAt));

    return sessions;
  }),

  // Set custom session duration for a user
  setUserSessionDuration: ownerOnly
    .input(z.object({
      userId: z.number(),
      durationMinutes: z.number().min(15).max(1440), // 15 min to 24 hours
    }))
    .mutation(async ({ input, ctx }) => {
      const drizzleDb = await getDb();
      if (!drizzleDb) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      // Update all active sessions for this user
      const activeSessions = await drizzleDb.select().from(userSessions)
        .where(and(eq(userSessions.userId, input.userId), eq(userSessions.isActive, true)));

      for (const session of activeSessions) {
        const newExpiresAt = new Date(session.lastActivity.getTime() + input.durationMinutes * 60 * 1000);
        await drizzleDb.update(userSessions).set({
          sessionDurationMinutes: input.durationMinutes,
          expiresAt: newExpiresAt,
        }).where(eq(userSessions.id, session.id));
      }

      // Log
      await drizzleDb.insert(activityLog).values({
        userId: ctx.user.id,
        userEmail: ctx.user.email || undefined,
        userRole: ctx.user.role,
        action: "cms.setSessionDuration",
        target: `user:${input.userId}`,
        details: JSON.stringify({ durationMinutes: input.durationMinutes }),
      });

      return { success: true };
    }),

  // Terminate a user's session (force logout)
  terminateUserSession: ownerOnly
    .input(z.object({ sessionId: z.number() }))
    .mutation(async ({ input, ctx }) => {
      const drizzleDb = await getDb();
      if (!drizzleDb) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      const [session] = await drizzleDb.select().from(userSessions).where(eq(userSessions.id, input.sessionId)).limit(1);
      if (!session) throw new TRPCError({ code: "NOT_FOUND", message: "Session not found" });

      await drizzleDb.update(userSessions).set({ isActive: false }).where(eq(userSessions.id, input.sessionId));

      // Log
      await drizzleDb.insert(activityLog).values({
        userId: ctx.user.id,
        userEmail: ctx.user.email || undefined,
        userRole: ctx.user.role,
        action: "cms.terminateSession",
        target: `session:${input.sessionId}`,
        details: JSON.stringify({ terminatedUserId: session.userId }),
      });

      return { success: true };
    }),

  // Get session info for a specific user (for the session indicator)
  getUserSession: publicProcedure
    .query(async ({ ctx }) => {
      if (!ctx.user) return null;
      const drizzleDb = await getDb();
      if (!drizzleDb) return null;

      const now = new Date();
      const [session] = await drizzleDb.select().from(userSessions)
        .where(and(
          eq(userSessions.userId, ctx.user.id),
          eq(userSessions.isActive, true),
          gte(userSessions.expiresAt, now),
        ))
        .orderBy(desc(userSessions.createdAt))
        .limit(1);

      return session || null;
    }),

  // Create or refresh a user session (called on login)
  createUserSession: publicProcedure
    .input(z.object({
      durationMinutes: z.number().default(180),
    }).optional())
    .mutation(async ({ ctx, input }) => {
      if (!ctx.user) throw new TRPCError({ code: "UNAUTHORIZED", message: "Not authenticated" });
      const drizzleDb = await getDb();
      if (!drizzleDb) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      const durationMinutes = input?.durationMinutes || 180;
      const now = new Date();
      const expiresAt = new Date(now.getTime() + durationMinutes * 60 * 1000);

      // Deactivate any existing active sessions for this user
      await drizzleDb.update(userSessions).set({ isActive: false })
        .where(and(eq(userSessions.userId, ctx.user.id), eq(userSessions.isActive, true)));

      // Create new session
      const [result] = await drizzleDb.insert(userSessions).values({
        userId: ctx.user.id,
        sessionDurationMinutes: durationMinutes,
        lastActivity: now,
        expiresAt,
        isActive: true,
        ipAddress: ctx.req.headers["x-forwarded-for"]?.toString().split(",")[0]?.trim() || ctx.req.ip || null,
        userAgent: ctx.req.headers["user-agent"] || null,
      });

      return { sessionId: result.insertId, expiresAt, durationMinutes };
    }),

  // Extend session (heartbeat)
  extendSession: publicProcedure.mutation(async ({ ctx }) => {
    if (!ctx.user) throw new TRPCError({ code: "UNAUTHORIZED", message: "Not authenticated" });
    const drizzleDb = await getDb();
    if (!drizzleDb) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

    const now = new Date();
    const [session] = await drizzleDb.select().from(userSessions)
      .where(and(
        eq(userSessions.userId, ctx.user.id),
        eq(userSessions.isActive, true),
        gte(userSessions.expiresAt, now),
      ))
      .orderBy(desc(userSessions.createdAt))
      .limit(1);

    if (!session) return { extended: false, reason: "no_active_session" };

    const newExpiresAt = new Date(now.getTime() + session.sessionDurationMinutes * 60 * 1000);
    await drizzleDb.update(userSessions).set({
      lastActivity: now,
      expiresAt: newExpiresAt,
    }).where(eq(userSessions.id, session.id));

    return { extended: true, expiresAt: newExpiresAt };
  }),

  // Deauthenticate (user-initiated logout from session)
  deauthenticate: publicProcedure.mutation(async ({ ctx }) => {
    if (!ctx.user) throw new TRPCError({ code: "UNAUTHORIZED", message: "Not authenticated" });
    const drizzleDb = await getDb();
    if (!drizzleDb) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

    // Deactivate all sessions for this user
    await drizzleDb.update(userSessions).set({ isActive: false })
      .where(and(eq(userSessions.userId, ctx.user.id), eq(userSessions.isActive, true)));

    return { success: true };
  }),

  // ─── Site Content (Disclaimer / Contribute / Enroll) ──────────────────────────────────────────────

  // Get all content for a section (public — used by DisclaimerModal, Contribute, Enroll)
  getSiteContent: publicProcedure
    .input(z.object({ section: z.string().optional() }))
    .query(async ({ input }) => {
      const drizzleDb = await getDb();
      if (!drizzleDb) return [];
      const conditions = input.section ? [eq(siteContent.section, input.section)] : [];
      const rows = await drizzleDb.select().from(siteContent)
        .where(conditions.length > 0 ? and(...conditions) : undefined)
        .orderBy(siteContent.section, siteContent.key);
      return rows;
    }),

  // Get all site content (CMS admin — returns all sections)
  getAllSiteContent: ownerOnly.query(async () => {
    const drizzleDb = await getDb();
    if (!drizzleDb) return [];
    const rows = await drizzleDb.select().from(siteContent)
      .orderBy(siteContent.section, siteContent.key);
    return rows;
  }),

  // Upsert a single content item (CMS admin)
  setSiteContent: ownerOnly
    .input(z.object({
      key: z.string().min(1).max(200),
      value: z.string(),
      type: z.enum(["text", "url", "boolean", "json"]).default("text"),
      section: z.string().min(1).max(100),
      label: z.string().optional(),
      description: z.string().optional(),
    }))
    .mutation(async ({ input, ctx }) => {
      const drizzleDb = await getDb();
      if (!drizzleDb) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      // Upsert: insert or update on duplicate key
      await drizzleDb.insert(siteContent).values({
        key: input.key,
        value: input.value,
        type: input.type,
        section: input.section,
        label: input.label || null,
        description: input.description || null,
        updatedBy: ctx.user.email || "super_admin",
      }).onDuplicateKeyUpdate({
        set: {
          value: input.value,
          type: input.type,
          label: input.label || null,
          description: input.description || null,
          updatedBy: ctx.user.email || "super_admin",
          updatedAt: new Date(),
        },
      });

      return { success: true };
    }),

  // Bulk upsert multiple content items at once (CMS admin)
  bulkSetSiteContent: ownerOnly
    .input(z.array(z.object({
      key: z.string().min(1).max(200),
      value: z.string(),
      type: z.enum(["text", "url", "boolean", "json"]).default("text"),
      section: z.string().min(1).max(100),
      label: z.string().optional(),
      description: z.string().optional(),
    })))
    .mutation(async ({ input, ctx }) => {
      const drizzleDb = await getDb();
      if (!drizzleDb) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      for (const item of input) {
        await drizzleDb.insert(siteContent).values({
          key: item.key,
          value: item.value,
          type: item.type,
          section: item.section,
          label: item.label || null,
          description: item.description || null,
          updatedBy: ctx.user.email || "super_admin",
        }).onDuplicateKeyUpdate({
          set: {
            value: item.value,
            type: item.type,
            label: item.label || null,
            description: item.description || null,
            updatedBy: ctx.user.email || "super_admin",
            updatedAt: new Date(),
          },
        });
      }

      return { success: true, count: input.length };
    }),

  // Delete a content item (resets to default)
  deleteSiteContent: ownerOnly
    .input(z.object({ key: z.string() }))
    .mutation(async ({ input }) => {
      const drizzleDb = await getDb();
      if (!drizzleDb) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });
      await drizzleDb.delete(siteContent).where(eq(siteContent.key, input.key));
      return { success: true };
    }),

  // ─── Mission Control (CMS) ───────────────────────────────────────────────────
  // Trigger a crawl mission immediately via super-admin token (bypasses cron schedule)
  triggerMission: ownerOnly
    .input(z.object({ id: z.number() }))
    .mutation(async ({ ctx, input }) => {
      const { triggerMissionNow } = await import("../missionScheduler");
      // Pass the super-admin username so the run log records who triggered it
      const username = ctx.user.name || ctx.user.email || "super_admin";
      return triggerMissionNow(input.id, username);
    }),

  // List all crawl missions (for CMS mission management panel)
  listMissions: ownerOnly.query(async () => {
    const { getMissions } = await import("../missionScheduler");
    return getMissions();
  }),

  // Get run history for a specific mission (last N runs)
  getMissionRuns: ownerOnly
    .input(z.object({
      missionId: z.number(),
      limit: z.number().min(1).max(100).default(20),
    }))
    .query(async ({ input }) => {
      const { getMissionRuns } = await import("../missionScheduler");
      return getMissionRuns(input.missionId, input.limit);
    }),

  // Get detailed mission info including last run stats
  getMissionDetails: ownerOnly
    .input(z.object({ id: z.number() }))
    .query(async ({ input }) => {
      const drizzleDb = await getDb();
      if (!drizzleDb) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });
      const { crawlMissions, missionRuns } = await import("../../drizzle/schema");
      const { eq, desc } = await import("drizzle-orm");
      const [mission] = await drizzleDb.select().from(crawlMissions).where(eq(crawlMissions.id, input.id));
      if (!mission) throw new TRPCError({ code: "NOT_FOUND", message: "Mission not found" });
      const lastRuns = await drizzleDb.select().from(missionRuns)
        .where(eq(missionRuns.missionId, input.id))
        .orderBy(desc(missionRuns.startedAt))
        .limit(10);
      return { mission, lastRuns };
    }),

  // Create a new crawl mission (records creator from the x-sa-token)
  createMission: ownerOnly
    .input(z.object({
      name: z.string().min(1),
      codename: z.string().optional(),
      description: z.string().optional(),
      targetAgencyIds: z.array(z.number()).optional(),
      targetCountries: z.array(z.string()).optional(),
      targetRegions: z.array(z.string()).optional(),
      targetTypes: z.array(z.string()).optional(),
      targetTopics: z.array(z.string()).optional(),
      cronExpression: z.string(),
      isRecurring: z.boolean().optional(),
      priority: z.enum(["low", "normal", "high", "critical"]).optional(),
      classification: z.enum(["UNCLASSIFIED", "CONFIDENTIAL", "SECRET", "TOP SECRET"]).optional(),
      minArticlesPerRun: z.number().optional(),
    }))
    .mutation(async ({ ctx, input }) => {
      const { createMission } = await import("../missionScheduler");
      const username = ctx.user.name || ctx.user.email || "super_admin";
      const credId = ctx.user.id || 0;
      return createMission({
        ...input,
        createdBy: username,
        createdByCredId: credId,
      });
    }),

  // Update an existing crawl mission
  updateMission: ownerOnly
    .input(z.object({
      id: z.number(),
      name: z.string().optional(),
      codename: z.string().optional(),
      description: z.string().optional(),
      targetAgencyIds: z.array(z.number()).optional(),
      targetCountries: z.array(z.string()).optional(),
      targetRegions: z.array(z.string()).optional(),
      targetTypes: z.array(z.string()).optional(),
      targetTopics: z.array(z.string()).optional(),
      cronExpression: z.string().optional(),
      isRecurring: z.boolean().optional(),
      priority: z.enum(["low", "normal", "high", "critical"]).optional(),
      classification: z.enum(["UNCLASSIFIED", "CONFIDENTIAL", "SECRET", "TOP SECRET"]).optional(),
      isActive: z.boolean().optional(),
      minArticlesPerRun: z.number().optional(),
    }))
    .mutation(async ({ input }) => {
      const { updateMission } = await import("../missionScheduler");
      const { id, ...rest } = input;
      await updateMission(id, rest as any);
      return { success: true };
    }),

  // Delete a crawl mission
  deleteMission: ownerOnly
    .input(z.object({ id: z.number() }))
    .mutation(async ({ input }) => {
      const { deleteMission } = await import("../missionScheduler");
      await deleteMission(input.id);
      return { success: true };
    }),
});
